In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = np.load("../logs/Curriculum/Hopper-v5/evaluations.npz", allow_pickle=True)

reward_main = data['results_main'].mean(axis=1)
reward_task = data['results_task'].mean(axis=1)
task = data['task']

In [3]:
reward_task

array([1320.62401899, 2063.56633398, 1625.97228357, 2042.70063212,
       2136.43108487, 2126.18338697, 2105.38497987, 2104.65803687,
       2094.55809905, 2098.19212535, 2139.81823859, 2146.31330103])

In [4]:
n_keys = data['results_dict'][0][0].keys()

results = np.zeros((len(data['results_dict']), len(n_keys)))

In [5]:
n_keys

dict_keys(['reward_x_velocity', 'reward_angle'])

In [6]:
for i in range(data['results_dict'].shape[0]):
    ith_results = data['results_dict'][i]
    for j in ith_results:
        for idx, value in enumerate(j):
            results[i][idx] += j[value]

In [7]:
results = results / data['results_dict'].shape[1]

In [8]:
results[:,0]

array([ 684.9372    , 1068.7791957 ,  842.28870146, 1063.93780334,
       1141.89371952, 1129.53813017, 1108.92473672, 1107.2863062 ,
       1098.65664883, 1102.40477894, 1142.46166863, 1149.57549323])

In [9]:
results[:,1]

array([635.68681898, 994.78713828, 783.68358211, 978.76282879,
       994.53736535, 996.6452568 , 996.46024315, 997.37173068,
       995.90145021, 995.78734642, 997.35656997, 996.7378078 ])